SELECT USER_ID, PRODUCT_ID
FROM (
    SELECT
        USER_ID,
        PRODUCT_ID,
        ROW_NUMBER() OVER (
            PARTITION BY USER_ID, PRODUCT_ID
            ORDER BY SALES_DATE
        ) AS RN
    FROM ONLINE_SALE
)
WHERE RN = 2
ORDER BY USER_ID, PRODUCT_ID DESC;