/*
SELECT SALES_YYYY
      ,SALES_MM
      ,GENDER
      ,COUNT(USER_ID) AS USERS
      FROM
(
SELECT DISTINCT TO_CHAR(SALES_DATE,'YYYY') AS SALES_YYYY
      ,TO_NUMBER(TO_CHAR(SALES_DATE,'MM')) AS SALES_MM
      ,UI.GENDER
      ,OS.USER_ID
  FROM ONLINE_SALE OS
  INNER JOIN USER_INFO UI 
  ON OS.USER_ID = UI.USER_ID
  AND UI.GENDER IS NOT NULL)
GROUP BY    SALES_YYYY, SALES_MM, GENDER
ORDER BY    1 ASC, 2 ASC, 3 ASC;
*/

SELECT
    T.YEAR,
    T.MONTH,
    U.GENDER,
    COUNT(DISTINCT T.USER_ID) AS USERS
FROM (
    SELECT
        USER_ID,
        TO_CHAR(SALES_DATE, 'YYYY') AS YEAR,
        TO_CHAR(SALES_DATE, 'MM') AS MONTH
    FROM ONLINE_SALE    
) T
JOIN USER_INFO U
    ON U.USER_ID = T.USER_ID
WHERE U.GENDER IS NOT NULL
GROUP BY T.YEAR, T.MONTH, U.GENDER
ORDER BY T.YEAR, T.MONTH, U.GENDER;