SELECT SALES_YYYY
      ,SALES_MM
      ,GENDER
      ,COUNT(DISTINCT USER_ID) AS USERS
      FROM
(
SELECT TO_CHAR(SALES_DATE,'YYYY') AS SALES_YYYY
      ,TO_NUMBER(TO_CHAR(SALES_DATE,'MM')) AS SALES_MM
      ,UI.GENDER
      ,OS.USER_ID
      ,OS.SALES_AMOUNT
  FROM ONLINE_SALE OS
  INNER JOIN USER_INFO UI 
  ON OS.USER_ID = UI.USER_ID
  AND UI.GENDER IS NOT NULL)
GROUP BY    SALES_YYYY, SALES_MM, GENDER
ORDER BY    1 ASC, 2 ASC, 3 ASC
    
    
    
    ;
  